feat: refactor to become platform-mesh operator (#2)

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -6,7 +6,7 @@ vars:
   CONTROLLER_TOOLS_VERSION: v0.18.0
   ENVTEST_VERSION: release-0.17
   CRD_DIRECTORY: config/crd
-  TEST_SETUP_DIRECTORY: setup/01-openmfp-system
+  TEST_SETUP_DIRECTORY: setup/01-platform-mesh-system
   GOMPLATE_VERSION: v4.3.0
   KUSTOMIZE_VERSION: v5.4.3
   OCM_VERSION: 0.24.0
@@ -71,34 +71,40 @@ tasks:
     cmds:
       - |
         export PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH
-        go test -timeout 25m -coverprofile=cover.out github.com/openmfp/openmfp-operator/test/e2e/kind {{.ADDITIONAL_COMMAND_ARGS}}
+        go test -timeout 25m -coverprofile=cover.out github.com/platform-mesh/platform-mesh-operator/test/e2e/kind {{.ADDITIONAL_COMMAND_ARGS}}
 
 
   test:
     deps: [mockery, setup:kind, setup:mkcert]
     env:
       GO111MODULE: on
-      # GH_TOKEN: "{{.WORKFLOW_GITHUB_PAT}}"
     cmds:
-      - |
-        if [ "$GITHUB_WORKFLOW" = "ci" ]; then
-          echo "Running tests in Github Actions"
-          echo "127.0.0.1 portal.dev.local kcp.api.portal.dev.local" | sudo tee -a /etc/hosts
-          GH_TOKEN=$WORKFLOW_GITHUB_PAT PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
-        else
-          # test if portal.dev.local and kcp.api.portal.dev.local are in /etc/hosts
-          if ! grep -q "portal.dev.local" /etc/hosts; then
-            echo "Missing portal.dev.local in /etc/hosts"
-            exit 1
-          fi
-          if ! grep -q "kcp.api.portal.dev.local" /etc/hosts;
-          then
-            echo "Missing kcp.api.portal.dev.local in /etc/hosts"
-            exit 1
-          fi
-          export PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH
-          go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
-        fi
+      - cmd: |
+            if [ "$GITHUB_WORKFLOW" = "ci" ]; then
+              echo "Running tests in Github Actions"
+              echo "127.0.0.1 portal.dev.local kcp.api.portal.dev.local" | sudo tee -a /etc/hosts
+              GH_TOKEN=$WORKFLOW_GITHUB_PAT PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}} || {
+                echo $GH_TOKEN
+                echo "---Listing HelmReleases"
+                kubectl get helmreleases -A
+                # ...
+                exit 1
+              }
+            else
+              # test if portal.dev.local and kcp.api.portal.dev.local are in /etc/hosts
+              if ! grep -q "portal.dev.local" /etc/hosts; then
+                echo "Missing portal.dev.local in /etc/hosts"
+                exit 1
+              fi
+              if ! grep -q "kcp.api.portal.dev.local" /etc/hosts;
+              then
+                echo "Missing kcp.api.portal.dev.local in /etc/hosts"
+                exit 1
+              fi
+              export PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH
+              go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
+            fi
+        ignore_error: false
         
   manifests:
     deps: [setup:controller-gen]
@@ -175,10 +181,10 @@ tasks:
         - istio-gateway
         - istio-base
         - example-resources
-      OPENMFP_PRIV_COMP:
-        sh: "{{.LOCAL_BIN}}/ocm get componentversions --latest github.com/openmfp/openmfp-priv --repo ghcr.io/openmfp/ocm -o json"
+      PLATFORM_MESH_COMP:
+        sh: "{{.LOCAL_BIN}}/ocm get componentversions --latest github.com/platform-mesh/platform-mesh --repo ghcr.io/platform-mesh -o json"
     cmds:
-      - OPENMFP_PRIV_COMP_VERSION=$(echo "{{ .OPENMFP_PRIV_COMP }}" | yq -r '.items[0].component.version') yq -i ".spec.version.semver = strenv(OPENMFP_PRIV_COMP_VERSION)" deployment/component-version.yaml
+      - PLATFORM_MESH_COMP_VERSION=$(echo "{{ .PLATFORM_MESH_COMP }}" | yq -r '.items[0].component.version') yq -i ".spec.version.semver = strenv(PLATFORM_MESH_COMP_VERSION)" deployment/component-version.yaml
       - for:
           var: SERVICES
-        cmd: COMP_VERSION=$(echo "{{ .OPENMFP_PRIV_COMP }}" | yq -r '.items[0].component.componentReferences[] | select(.name == "{{ .ITEM }}").version') yq -i ".spec.sourceRef.resourceRef.version = strenv(COMP_VERSION)" deployment/{{ range splitList "-" .ITEM }}{{ . }}{{ end }}/resource.yaml
+        cmd: COMP_VERSION=$(echo "{{ .PLATFORM_MESH_COMP }}" | yq -r '.items[0].component.componentReferences[] | select(.name == "{{ .ITEM }}").version') yq -i ".spec.sourceRef.resourceRef.version = strenv(COMP_VERSION)" deployment/{{ range splitList "-" .ITEM }}{{ . }}{{ end }}/resource.yaml
