iterate: test
On-behalf-of: @SAP angel.kafazov@sap.com
Signed-off-by: Angel Kafazov <akafazov@cst-bg.net>

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -81,33 +81,35 @@ tasks:
       # GH_TOKEN: "{{.WORKFLOW_GITHUB_PAT}}"
     cmds:
       - |
-        if [ "$GITHUB_WORKFLOW" = "ci" ]; then
-          echo "Running tests in Github Actions"
-          echo "127.0.0.1 portal.dev.local kcp.api.portal.dev.local" | sudo tee -a /etc/hosts
-          GH_TOKEN=$WORKFLOW_GITHUB_PAT PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
-        else
-          # test if portal.dev.local and kcp.api.portal.dev.local are in /etc/hosts
-          if ! grep -q "portal.dev.local" /etc/hosts; then
-            echo "Missing portal.dev.local in /etc/hosts"
-            exit 1
-          fi
-          if ! grep -q "kcp.api.portal.dev.local" /etc/hosts;
-          then
-            echo "Missing kcp.api.portal.dev.local in /etc/hosts"
-            exit 1
-          fi
-          export PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH
-          go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
-        fi
+        docker pull ghcr.io/platform-mesh/security-operator:v0.0.22
+      # - |
+      #   if [ "$GITHUB_WORKFLOW" = "ci" ]; then
+      #     echo "Running tests in Github Actions"
+      #     echo "127.0.0.1 portal.dev.local kcp.api.portal.dev.local" | sudo tee -a /etc/hosts
+      #     GH_TOKEN=$WORKFLOW_GITHUB_PAT PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
+      #   else
+      #     # test if portal.dev.local and kcp.api.portal.dev.local are in /etc/hosts
+      #     if ! grep -q "portal.dev.local" /etc/hosts; then
+      #       echo "Missing portal.dev.local in /etc/hosts"
+      #       exit 1
+      #     fi
+      #     if ! grep -q "kcp.api.portal.dev.local" /etc/hosts;
+      #     then
+      #       echo "Missing kcp.api.portal.dev.local in /etc/hosts"
+      #       exit 1
+      #     fi
+      #     export PATH=$(pwd)/{{.LOCAL_BIN}}:$PATH
+      #     go test -timeout 25m -coverprofile=cover.out ./... {{.ADDITIONAL_COMMAND_ARGS}}
+      #   fi
         
-      - |
-        kubectl get pods -A -o wide
-        kubectl get helmreleases -A
-        kubectl get deployments -A
-        kubectl get svc -A
-        kubectl get secrets -A
-        kubectl get crds -A
-        kubectl get nodes -o wide
+      # - |
+      #   kubectl get pods -A -o wide
+      #   kubectl get helmreleases -A
+      #   kubectl get deployments -A
+      #   kubectl get svc -A
+      #   kubectl get secrets -A
+      #   kubectl get crds -A
+      #   kubectl get nodes -o wide
 
   manifests:
     deps: [setup:controller-gen]
